### ISSUE TITLE
Buffered up-sampling reproject in ETL

### ISSUE THREAD

**Issue by echeipesh** [locationtech/geotrellis#2170]
Up-sampling reproject using GDAL:
<img width="322" alt="gdal-rep" src="https://cloud.githubusercontent.com/assets/1158084/25506567/467e64a2-2b75-11e7-9ca9-0446c467bd05.png">

Up-sampling reproject using ETL buffered reproject:
<img width="323" alt="etl-rep" src="https://cloud.githubusercontent.com/assets/1158084/25506574/53d41f02-2b75-11e7-926a-9490f730c9e6.png">

Call site: https://github.com/locationtech/geotrellis/blob/master/spark-etl/src/main/scala/geotrellis/spark/etl/Etl.scala#L199-L201

This appears like a legitimate way to call the reproject, if not parameter validation may be required.

**Comment by pomadchin** [comment]
Small info about bug: 

Not related to: 

* ETL itself
* tiling method (buffered / per-tile)
* resampling method 
* `mapToGrid` function (i had an experiment with using a different implementation, based on GDAL)

Probably this issue happens due to digits rounding (the more zoom level is the more error we have)? Or somewhere a bit incorrect logic used?

**Comment by echeipesh** [comment]
Related investigations: https://github.com/locationtech/geotrellis/issues/2170

**Comment by lossyrob** [comment]
This is caused by the fact we reproject to the current cell size (or what the reproject logic matches the source cell size to the target CRS), and then resample. When you reproject with `Raster.Options(targetCellSize=Some(cellSize))`, you get good results:

Up-sampling reproject using GDAL
<img width="1484" alt="screen shot 2017-05-27 at 2 18 39 am" src="https://cloud.githubusercontent.com/assets/2320142/26518663/e9aeb8a6-4282-11e7-98af-bc396cdf9896.png">

With this code:

```scala
val path = "cdl_orig_small.tif"
val gt = SinglebandGeoTiff(path)

val reprojected =
  gt.raster.reproject(
    gt.crs,
    WebMercator
  )

val resampled = 
  reprojected.resample(
    RasterExtent(
      reprojected.extent, 
      CellSize(2.388657133911758,2.388657133911758)
    )
  )

GeoTiff(resampled, WebMercator).write("geotrellis-single-small-out.tif")
```
we get

<img width="1481" alt="screen shot 2017-05-27 at 2 19 01 am" src="https://cloud.githubusercontent.com/assets/2320142/26518675/1936e26a-4283-11e7-9e52-d5c1971a16ef.png">

Which is bad. When we resample with a targetCellSize, with this code:

```scala
import geotrellis.raster.reproject.Reproject

val path = "cdl_orig_small.tif"
val gt = SinglebandGeoTiff(path)

val reprojected =
  gt.raster.reproject(
    gt.crs,
    WebMercator,
    Reproject.Options(
      targetCellSize = Some(CellSize(2.388657133911758,2.388657133911758))
    )
  )

GeoTiff(reprojected, WebMercator).write("geotrellis-single-small-RP-out.tif")
```

It matches the GDAL output:

<img width="1481" alt="screen shot 2017-05-27 at 2 19 11 am" src="https://cloud.githubusercontent.com/assets/2320142/26518683/51321d4c-4283-11e7-88e5-9d3d769509ca.png">

The fix here, for reproject of an RDD, we need to account for the targetCellSize if the layout we are reprojecting to has a smaller cell size than what would be computed by reprojection without that option.
