### ISSUE TITLE
Specify precision model for GeometryFactory based on configuration

### ISSUE THREAD

**Issue by lossyrob** [locationtech/geotrellis#2219]

**Comment by echeipesh** [comment]
For context: Some JTS operations are not fully robust and [PrecisionModel](https://locationtech.github.io/jts/javadoc/org/locationtech/jts/geom/PrecisionModel.html) sometimes needs to be tuned to avoid producing invalid geometries for a given operation/geometry combination.

This solution is not optimal because it introduces an application scoped configuration for input scoped parameter, but some configuration is better than none.
