### ISSUE TITLE
Make Amazon S3 backend more configurable

### ISSUE THREAD

**Issue by hectcastro** [locationtech/geotrellis#2304]
Right now, it is not straightforward to override the Amazon S3 client configuration. It would be great if there was a way to allow users to configure things like maximum connections, timeouts, retry polices, etc. Perhaps even better might be for the backend to accept an S3 client object for use.

See: https://github.com/locationtech/geotrellis/blob/v1.1.1/s3/src/main/scala/geotrellis/spark/io/s3/S3Client.scala#L135-L144

**Comment by lossyrob** [comment]
You can pass in your own AwsS3Client here: https://github.com/locationtech/geotrellis/blob/5cb43cb8ccec72e841537e765ae9db6f3f069620/s3/src/main/scala/geotrellis/spark/io/s3/AmazonS3Client.scala#L43

You can also override S3LayerReader and family vie overriding https://github.com/locationtech/geotrellis/blob/5cb43cb8ccec72e841537e765ae9db6f3f069620/s3/src/main/scala/geotrellis/spark/io/s3/S3ValueReader.scala#L37. Not my favorite design pattern, but it's possible. That's how we create the MockS3Client stuff, a la https://github.com/locationtech/geotrellis/blob/5cb43cb8ccec72e841537e765ae9db6f3f069620/s3-testkit/src/main/scala/geotrellis/spark/io/s3/testkit/MockS3CollectionLayerReader.scala#L28

The `val` in S3ValueReader should really be a `def`, so that the overriding class isn't forced to use a `val`. Otherwise I believe what you want is possible.

I'm going to mark this as 1.2, and include that val -> def change, and some documentation around how to do this.

**Comment by echeipesh** [comment]
@hectcastro is that the level you were thinking at or were you hoping to expose those settings somehow to typesafe config ?

**Comment by hectcastro** [comment]
Na, this is actually good. I was confused with how the defaults were being applied. With regard to the Typesafe config, I think being able to provide the entire client is better given that there are a large number of client settings.

In the process of validating this, I noticed that the `com.amazonaws.services.s3.AmazonS3Client` is deprecated, which makes the the `AmazonS3ClientBuilder` approach to building an S3 client (since SDK 1.11.84) incompatible with the `geotrellis.spark.io.s3.AmazonS3Client` constructor: https://github.com/locationtech/geotrellis/blob/v1.1.1/s3/src/main/scala/geotrellis/spark/io/s3/AmazonS3Client.scala#L43

Are there any tricks into coercing it? If not, I can create a separate issue to track that deprecation.

**Comment by echeipesh** [comment]
I don't see a straight forward way to coerce it, will probably require changing API and a tracking issue.

**Comment by hectcastro** [comment]
I created https://github.com/locationtech/geotrellis/issues/2399 to track the `geotrellis.spark.io.s3.AmazonS3Client` constructor issue. Leaving this open because Rob wanted to use it to track the `val` -> `def` change.
