### ISSUE TITLE
HadoopAttributeStore Cannot List Available Attributes

### ISSUE THREAD

**Issue by jbouffard** [locationtech/geotrellis#2624]
It appears that `HadoopAttributeStore` is unable to list the attribute files of layers that are saved locally

```
scala> h.write[TileLayerMetadata[SpatialKey]](LayerId("test-layer-2", 11), "metadata", layer.metadata)

scala> h.availableAttributes(LayerId("test-layer-2", 11))
res16: Seq[String] = Vector()

scala> h.attributePath(LayerId("test-layer-2", 11), "metadata")
res17: org.apache.hadoop.fs.Path = file:/tmp/test-attributes/_attributes/test-layer-2___11___metadata.json
```

I have not tried getting the attributes from a layer that was saved to hdfs, so I'm not sure if this issue appears in that case.

**Comment by jbouffard** [comment]
I don't think it'd work regardless of where the attributes are saved to due to this typo https://github.com/locationtech/geotrellis/blob/master/spark/src/main/scala/geotrellis/spark/io/hadoop/HadoopAttributeStore.scala#L71

**Comment by zhaoxianwei** [comment]
@jbouffard Execuse me, I have a question to ask, I want to know why the data written by S3AttributeStore is not compatible with the data written by HadoopAttributeStore. What is the reason for this design? I imported the data through S3AttributeStore, but I can't read it through HadoopAttributeStore because the attribute file naming format is inconsistent. I am looking forward to your reply, thank you

**Comment by zhaoxianwei** [comment]
This is S3AttributeStore's attributePath
`  def attributePath(id: LayerId, attributeName: String): String =
    path(prefix, "_attributes", s"${attributeName}${SEP}${id.name}${SEP}${id.zoom}.json")`
And this is the  HadoopAttributeStore's attribute path
` def attributePath(layerId: LayerId, attributeName: String): Path = {
    val fname = s"${layerId.name}${SEP}${layerId.zoom}${SEP}${attributeName}.json"
    new Path(attributePath, fname)
  }`
Why can't they be unified?
