### ISSUE TITLE
Structured COG band subsetting

### ISSUE THREAD

**Issue by echeipesh** [locationtech/geotrellis#2706]
Current multiband COG readers still produce all of the bands from the GeoTiff.
However, its possible that the user knows that useful information exists only in subset of the bands and wishes to read exclusively those layers. GeoTiffs that use band-interleave naturally lend themselves to this optimization.

The main concerns is how to deal with invalid band selection. Currently you get "all the bands", whatever that is, so there is no opportunity for errors. Given band subset of [1,2,100] its not desirable to fail the whole query if some of the tiffs do not have band 100. Two choices are fill missing bands with `NODATA` tiles or return `Array[Option[Tile]]`. The latter is more explicit and more efficient because avoids needing to call `.isNoDataTile` to verify query results. However its not consistent with current API. Part of the issue here is to think through the implications and possibly establish a new convention for when we querying for band subsets.

Although we are already in 2.0.0-RC1 this should be developed with intent to back-port the addition to 2.1 branch.

**Comment by jbouffard** [comment]
I personally don't like the first option of returning missing bands with `NODATA` since that just seems like the reader is failing silently. The other alternative seems okay, but I think that throwing an error might be better. If there's a failure in the reading stage, then that means the user has an incorrect assumption about the data they're working with, which should be known as soon as possible.

Regardless of what we decided to return, though, I feel that this feature should just be temporary to the 2.0 release. In my opinion, it doesn't make sense to have two separate read methods for the `ValueReader`s where one reads the whole `Tile` while the other just reads a subset of bands. Rather it should just be a single `read` method that gives the decided return type. What that type is is something we should discus more here #2732

**Comment by moradology** [comment]
The main issue `Option` has, and a cause for the complaints some have of 'maybeitis' in functional code, is that `None` is not supposed to serve as a stand-in for ⊥: if it can mean `exception encountered` and `value not there - no exceptional state encountered`, it is doing a disservice to both cases.

Because this code reaches out into the world and does stuff, exceptions aren't really avoidable. Because we need to call out such exceptional cases *as well as* represent successful computations which return `None`, I think the best bet would be for us to wrap code like this up in `IO`. `IO[Array[Option[Tile]]]` means that any `None` cases should be given the full semantic treatment and that we can always get at thrown exceptions in our callsite (`IO.attempt` converts `IO[A]` to `IO[Either[Throwable, A]]`)

**Comment by pomadchin** [comment]
@jbouffard so you think that `bandSubset` method and the entire tile read should be the same method? 

Separate methods were done 1. because of a different signature 2. different semantics. I can see that probably it makes sense just to call a `bandSubset` function in other `read` functions.

I also want to add that I'm very happy to see and agree with @moradology suggestion about exceptions handle via `IO` monad, but it's more a part of #2732. It looks like `IO` thing won't happen in terms of 2.0 though.

**Comment by pomadchin** [comment]
@jbouffard yea, your idea would work only if this method would fail on any incorrect bands. I don't buy your love to `Exceptions` :D

**Comment by moradology** [comment]
Here's how you deal with `IO[Either[Throwable, A]]`:
```scala
val x = someIO.attempt
x map {
  case Right(success) => success
  case Left(ElementNotFoundException) => ???
  case Left(_) => ???
}```

**Comment by jbouffard** [comment]
@pomadchin I wouldn't say that I have a love for `Exception`s haha, just that I think they have a place in IO. I do like the `IO` monad, but I just think that it adds more complexity than is needed to the API. By having the method just throw an error, the user will be able to decide how they want to handle things.

**Comment by moradology** [comment]
For those poor, confused souls, this might be OK:
```scala
try {
  someIO map { result => ??? }.runUnsafeSync
} catch {
  case MyException(_) => ???
}
```

**Comment by pomadchin** [comment]
@jbouffard also from the last @moradology example it's clear how we can get async api for free (we wanted to investigate it https://github.com/locationtech/geotrellis/issues/2306). 
The next thing is that you can compose `effects` via `IO` monad, and not to try catch each particular block, semantics of `IO` itself mean `encoding side effects as pure values, capable of expressing both (a)synchronous computations`.

It's a big question what is better to `throw new Exception` (which would always be an unexpected thing) or to add some semantics into the type description. 

For sure every time i mention `IO` it's in terms of our future possible solution.

**Comment by jbouffard** [comment]
@pomadchin Should we close this issue and move the discussion elsewhere?

**Comment by pomadchin** [comment]
@jbouffard not sure yet, will figure it out!

**Comment by pomadchin** [comment]
Closed here https://github.com/locationtech/geotrellis/pull/2775
