### ISSUE TITLE
Ingest landsat8 tiffs using EPSG:32650 failed

### ISSUE THREAD

**Issue by tosen1990** [locationtech/geotrellis#2826]
All I want is just to tile the tiff using the original projection which I read from landat8 tiffs like ESPG:32650. And I'v tried many different tiffs of scenes. When ingesting using projection EPGS:32650,the extent error throws out always. But when change it to EPSG:4326 /WebMecaotr,I always success. I am not sure this is a bug? I've never seen anyone use this kind of project for ingesting for now.
```scala 
val targetLayoutScheme = ZoomedLayoutScheme(CRS.fromName("EPSG:32650"), 256) 
acc :+ rdd.reproject(targetLayoutScheme, bufferSize = 30, Reproject.Options(method = Bilinear, errorThreshold = 0)) Caused by: geotrellis.vector.ExtentRangeError: Invalid Extent: xmin must be less than xmax (xmin=500001.0179734276, xmax=500000.97161722643)
```
Scenes of tests downloaded from aws are including:
- LC08_L1TP_123032_20180118_20180206_01_T1
- LC08_L1TP_123032_20180102_20180104_01_T1
- LC81220322015019LGN00

**Comment by pomadchin** [comment]
Hey @tosen1990 thanks a lot for your report!

It looks like indeed we don't support this projection well, it's a [proj4 bug](https://github.com/locationtech/geotrellis/blob/master/proj4/src/test/resources/proj4-epsg.csv#L3916). I investigated this morning a lil bit more; it looks like we need to use `ExtendedTranverseMercator` to handle `UTM` projections:
* https://github.com/OSGeo/proj.4/issues/316
* https://github.com/locationtech/proj4j/blob/master/src/main/java/org/locationtech/proj4j/proj/ExtendedTransverseMercatorProjection.java

Aslo mb it's a good point to start swtitching to locationtech proj4j (if it's published for sure), otherwise it looks like we need to accept [this pr](https://github.com/locationtech/proj4j/pull/14) and to fix [these tests](https://github.com/locationtech/geotrellis/blob/master/proj4/src/test/resources/proj4-epsg.csv#L3916).

**Comment by pomadchin** [comment]
@tosen1990 are you on 2.1? // just to confirm

**Comment by tosen1990** [comment]
@pomadchin yes,I'm on gt 2.1.

**Comment by pomadchin** [comment]
Looked closer into this issue, and yes there is a problem in `proj4` projections into some of UTM projections.  So the problem of UTM projections that all these projections are used for some local math (that's thy there are so many UTM zones) and it makes no sense as a destination projection for general use. `ZoomedLayoutScheme` computes some particular tile global location basing on the projection WorldExtent information and it's obviously is not supported by UTM projections. 

The solution would be probably to implement a different `ZonedLayoutScheme`, but at this point we don't support UTM zones as target Global projections.

But the proper solution would be to use a different layout scheme: `FloatingLayoutScheme` or `LocalLayoutScheme` as this CRS is local.

**Comment by tosen1990** [comment]
@pomadchin Totally understand and thanx for your time.
