### ISSUE TITLE
Dynamic release of GeoTIFF as TMS

### ISSUE THREAD

**Issue by joeal86** [locationtech/geotrellis#2828]
Wrong! Wrong! I'm going to run away.
![5](https://user-images.githubusercontent.com/35072225/49213996-9b734400-f400-11e8-833e-afdb71f192f0.png)

**Comment by pomadchin** [comment]
Hey @joeal86 what’s wrong there?

**Comment by pomadchin** [comment]
It looks like you've copied this code from some site. I can recommend you to get familiar with our [docs](https://geotrellis.readthedocs.io/en/latest/) and with some demos: https://github.com/geotrellis/geotrellis-chatta-demo and https://github.com/geotrellis/geotrellis-landsat-tutorial 

You can always ask any questions in our [gitter channel](https://gitter.im/geotrellis/geotrellis) as well.

**Comment by pomadchin** [comment]
Closing this issue due to lack of feedback, any useful information and even code (it has a screenshot of code for some reason instead of code insertaion using git md). Probably we need to add a couple of words about issue creation rules into [CONTRIBUTING.rst](https://github.com/locationtech/geotrellis/blob/master/docs/CONTRIBUTING.rst).

However @joeal86 feel free to reopen this issue / create a new one with more details and without screenshots of your code.
