### ISSUE TITLE
`CRS.fromWKT` doesn't handle WKT with no EPSG record.

### ISSUE THREAD

**Issue by metasim** [locationtech/geotrellis#2871]
## Input
This WKT is from calling `org.opengis.referencing.crs.CoordinateReferenceSystem#toWKT` on data read from a random shapefile via GeoTools.

```
CRS.fromWKT("""|GEOGCS["GCS_WGS_1984",
               |DATUM["D_WGS_1984",
               |SPHEROID["WGS_1984", 6378137.0, 298.257223563]],
               |PRIMEM["Greenwich", 0.0],
               |UNIT["degree", 0.017453292519943295],
               |AXIS["Longitude", EAST],
               |AXIS["Latitude", NORTH]]
               |""".stripMargin.replaceAll("\n",""))

```

## Output

```
None.get
java.util.NoSuchElementException: None.get
	at scala.None$.get(Option.scala:347)
	at scala.None$.get(Option.scala:345)
	at geotrellis.proj4.io.wkt.WKT$.getEpsgCode(WKT.scala:70)
	at geotrellis.proj4.CRS$.fromWKT(CRS.scala:87)
```

Related: #2870

**Comment by metasim** [comment]
I also think it would be beneficial for `CRS.fromWKT` to automatically call the `.replaceAll("\n","")`.

**Comment by CloudNiner** [comment]
I'm under the impression from the way the issue here is written that you'd expect the WKT string you provided to be successfully parsed by the `CRS.fromWKT` method. Is that true? If so, #3074 updates the CRS.fromWKT to return an `Option[CRS]` rather than crash outright. 

As far as I can tell, with existing code, we're only able to parse WKT strings that we can retrieve an [EPSG code from](https://github.com/locationtech/geotrellis/blob/master/proj4/src/main/scala/geotrellis/proj4/CRS.scala#L99) or have [already parsed parameters](https://github.com/locationtech/geotrellis/blob/master/proj4/src/main/scala/geotrellis/proj4/CRS.scala#L62) for. Unless I'm missing the correct call using some other method, this issue will require a bit more effort to resolve since this WKT string is missing an authority.

**Comment by metasim** [comment]
@CloudNiner You're correct; I filed this bug before I understood that it only worked for embedded EPSG codes. However, I do think that it will also throw (or swallow?) an exception in the case where it does have an embedded EPSG code, but also has newlines.

**Comment by CloudNiner** [comment]
Sounds good. For now I'll just check for and address the newline issue if that's still a problem.

**Comment by CloudNiner** [comment]
Updated #3074 -- WKTParser now automatically strips newlines before attempting to parse. There was an old test that demos how newlines can be stripped manually, updated that to just compare a multiline vs single line string: 24c17c086574be93b3b92a8811692a77e887979f

**Comment by metasim** [comment]
Should this be closed then? The "convert all the things" version is probably more of a Proj4j issue anyway...

https://github.com/locationtech/proj4j/issues/49

**Comment by CloudNiner** [comment]
Certainly looks like it. Will close with the merging of #3074.
