### ISSUE TITLE
Allow vectortile.Layer to pass a valid 'id' to internal.vector_tile.Tile.Layer

### ISSUE THREAD

**Issue by kevinmhinson** [locationtech/geotrellis#2884]
Hi!  I'm using GeoTrellis and VectorPipe to create MapBox vector tiles.  The problem I have is...  I need to be able to write a top level 'id' in each Feature (not as part of 'properties')...  and in `vectortile.Layer.unfeature()`, the arg `id: Option[Long]` passed to `vectortile.internal.vector_tile.Tile.Feature` is hard-coded in .unfeature() as `None`.

To solve this for my purposes, I forked and compiled locally with a `Map[String,Value] => Option[Long]` function hard coded in `Layer.unfeature()` to create an 'id' from 'data' to pass to `vt.Tile.Feature`.  This worked, and the output .PBFs had the expected 'id' in them.

I'm trying to think through how else users might want to create an 'id'...  maybe a random Long would be sufficient for some, but that could still be coded into a 'data' => 'id' function.

I believe this would be a common pattern, to want an 'id' and to be able to create from the metadata.  It looks like the VectorPipe API has completely changed since two days ago, but it used to be in `Collate.generically()` where a `vectortile.StrictLayer` is constructed.  If there was a way to pass in a `Map[String,Value] => Option[Long]` function to Layer/StrictLayer/LazyLayer for `Layer` to use in .unfeature() to convert 'data' to valid 'id' instead of hard-coding as None...  I think that would be a common use case.

**Comment by jpolchlo** [comment]
Looks like you're absolutely right.  The GeoJSON spec indeed does include an optional `id` property.  For reference, https://tools.ietf.org/html/rfc7946#page-11 shows that this identifier _should_ be placed into a separate top-level field of the feature.  Given that, it's not clear that the right solution is simply to allow properties to be mined for this data, since that may imply that the id field will be redundantly serialized to both the `properties` and `id` field.  We may want to include a proper `id` field in `Feature[G, D]` itself and let that change propagate into `vectortile` naturally.

Any thoughts, @echeipesh, @pomadchin ?

**Comment by echeipesh** [comment]
A breadcrumb for where VectorTile feature are being created:

https://github.com/locationtech/geotrellis/blob/f8af6e6d72749b8fb175a0c44cbc7d027a940686/vectortile/src/main/scala/geotrellis/vectortile/Layer.scala#L127-L137
