### ISSUE TITLE
S3RangeReader will always produce HEAD request

### ISSUE THREAD

**Issue by echeipesh** [locationtech/geotrellis#2889]
In order to produce object metadata and its overall size the underlying S3 client will issue a `HEAD` request: 

https://github.com/locationtech/geotrellis/blob/f86ef9eb459b219a5ce8e082f7b8d1f9431a6995/s3/src/main/scala/geotrellis/spark/io/s3/util/S3RangeReader.scala#L39-L42

This is problematic for two reasons:
- Sometimes the object ACT will not allow `HEAD` requests, resulting in error `400`
- In most use cases `totalLength` is not used and is not important.

To expand on the second point, the GeoTrellis GeoTiffReader will read from the start of the file until it consumes the full header. At that point it will use the offset information from the GeoTiff header to read the data segments.

Note that `HttpRangeReader` already has logic for this case:

https://github.com/locationtech/geotrellis/blob/f86ef9eb459b219a5ce8e082f7b8d1f9431a6995/spark/src/main/scala/geotrellis/spark/io/http/util/HttpRangeReader.scala#L38-L64

At a minimum the `totalSize` should be turned into `lazy val` which would avoid the issue in most cases. S3RangeReader should also have a constructor flag to avoid head requests. This should cause re-evaluation of the `RangeReader` interface, maybe we don't need that method at all?

**Comment by metasim** [comment]
RasterFrames has/had a workaround using a copy of `HttpRangeReader`:

https://github.com/locationtech/rasterframes/blob/9ced1ec19ead0a9225fb8349b7c0b5b233b79df5/core/src/main/scala/astraea/spark/rasterframes/ref/HttpRangeReader.scala#L42-L49

**Comment by jbouffard** [comment]
@echeipesh I'm a little confused as to how `totalLength` is rarely used inside `S3RangeReader`. It looks like it's [always checked against](https://github.com/locationtech/geotrellis/blob/f86ef9eb459b219a5ce8e082f7b8d1f9431a6995/util/src/main/scala/geotrellis/util/RangeReader.scala#L27-L36) when doing range reading.

**Comment by pomadchin** [comment]
@jbouffard it is only used in [clipToSize](https://github.com/locationtech/geotrellis/blob/f86ef9eb459b219a5ce8e082f7b8d1f9431a6995/util/src/main/scala/geotrellis/util/RangeReader.scala#L27) and [readAll](https://github.com/locationtech/geotrellis/blob/f86ef9eb459b219a5ce8e082f7b8d1f9431a6995/util/src/main/scala/geotrellis/util/RangeReader.scala#L41). `totalLength` is already a [lazy val in S3RangeReader](https://github.com/locationtech/geotrellis/blob/master/s3/src/main/scala/geotrellis/store/s3/util/S3RangeReader.scala#L53). 

I think the issue is to check can we do smth with [this HeadRequest](https://github.com/locationtech/geotrellis/blob/master/s3/src/main/scala/geotrellis/store/s3/util/S3RangeReader.scala#L44) usage since it is not always accepted by the S3 bucket policies. If yes - the same constructor can be used as for the [HttpRangeReader](https://github.com/locationtech/geotrellis/blob/master/spark/src/main/scala/geotrellis/spark/store/http/util/HttpRangeReader.scala#L34)

**Comment by echeipesh** [comment]
@jbouffard Thats right, its part of that internal function but its rarely/ever used as a public method of the interface. The fact that we use it in `clipToSize` can be and should be avoided. The issue mentions `HttpRangeReader` dealing with the same issue so its worth while to take a look at how it's handled there.
