### ISSUE TITLE
Unable to find region in custom s3Client

### ISSUE THREAD

**Issue by kitchdev** [locationtech/geotrellis#2928]
I recently followed your tutorial for overriding the defualt geotrellis-s3-Client configuration from:
https://geotrellis.readthedocs.io/en/latest/guide/examples.html
```scala
import geotrellis.spark.io.s3._
import com.amazonaws.services.s3.{AmazonS3Client=>AWSAmazonS3Client}

val aws: AWSAmazonS3Client = ??? /* Special configuration happens here */
val specialS3client = new AmazonS3Client(aws)

val attributeStore = new S3AttributeStore("my-bucket", "my-prefix") {
   override def s3Client = specialS3Client
}

val valueReader = new S3ValueReader(attributeStore) {
   override def s3Client = specialS3Client
}
```
This appears to be functional at first, but when run in a spark job I receive this error after some processing: https://pastebin.com/YRq017br  

It seems like the overidden client somehow loses it's region config somehow.
I'm currently using a Linux Mint 19 Cinnamon 3.8.9 OS and my sbt version is 1.2.8

I've created a public repo with the necessary code in order to reproduce the problem:
https://github.com/kitchdev/geotiff-s3-tiler

A detailed setup is included in the README but basically, you just need an AWS ACCESS & SECRET KEY for the "us-east-2" region to recreate the error. Load sbt and use the `run` command.

Any help you guys can give would be very appreciated.

**Comment by pomadchin** [comment]
Hey @kitchdev I think it is a problem of a poor API here: 

```scala
@transient lazy val amazonS3 = 
  AmazonS3ClientBuilder
    .standard()
    .withCredentials(credentialsProvider)
    .withRegion(region)
    .build()

val writer = 
  new S3LayerWriter(attributeStore, bucket, prefix) {
    override def rddWriter = new S3RDDWriter {
      def getS3Client = () => amazonS3
    }
  }
```

Because of a generic nature of all readers, attribute store and readers / writers have a different S3Client. [Mock Writer example from tests](https://github.com/locationtech/geotrellis/blob/master/s3-testkit/src/main/scala/geotrellis/spark/io/s3/testkit/MockS3LayerWriter.scala)

**Comment by eraigosa** [comment]
the solution proposed by @pomadchin leads to the #2929 because when you write “override def rddWriter” the generated code is going to be an object not serializable that can’t be distributed, and in this case, you can’t use a “val” (unfortunately)
please read #2929 for more detail.
Now, for this error, I would recommend you to use some of the solution described here
[(https://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/setup-credentials.html)]
to test it you can use “export AWS_REGION=ap-northeast-1” but I strongly recommend to use another option in a production environment like, for example, the “.aws/config” file.

Alternatively, you could set the aws region (and other parameters) programmatically, I’ve ever used it but it makes sense if you need to change dynamically your region. 
[https://stackoverflow.com/questions/33828588/spark-cannot-read-files-stored-on-aws-s3-in-frankfurt-region-ireland-region-wor]

this is the code I recommend after setting the region in the aws config file

> // Create the writer that we will use to store the tiles in the local catalog.
  val writer: S3LayerWriter = new S3LayerWriter(attributeStore, bucketName, prefix) {
    //      override def rddWriter = new S3RDDWriter {
    //        @transient lazy val newClient = new AmazonS3Client(
    //          AmazonS3ClientBuilder
    //            .standard()
    //            .withCredentials(credentialsProvider)
    //            .withRegion(region)
    //            .build()
    //        )
    //        override def getS3Client = () => { newClient }
    //        println(getS3Client)
    //      }
  }

PD: @pomadchin thanks for your help. Really appreciated. 😊
PD: try to avoid using @transient lazy

**Comment by pomadchin** [comment]
hey @eraigosa sometimes `transient lazy` can be faster than anything else in case of creating instances of heavy objects; for instance `loggers`, `thread pools`, etc.
