### ISSUE TITLE
Logging library clashes

### ISSUE THREAD

**Issue by bogdanghit** [locationtech/geotrellis#3037]
We are facing an instantiation error when using the scala-logging library. This [link](https://github.com/akka/alpakka-kafka/issues/99) provides an workaround which requires compiling the library with this dependency: "com.typesafe.scala-logging" %% "scala-logging-slf4j" % "2.1.2". How can we build this library to include this dependency?

**Comment by pomadchin** [comment]
Hey @bogdanghit can you describe exactly what issue do you have? I would say that probably you can resolve your issue via shading our dep.

**Comment by echeipesh** [comment]
Sounds like a related problem to: https://github.com/locationtech/rasterframes/issues/293
May be fixed by https://github.com/locationtech/geotrellis/pull/3115

I'd have to code-dive to find out the exact cause again but something in in `scala-logging` switched from being a `trait` to being a `class` and depending what is on the class path you will get `InstantiationError` if you try to `new` up a `trait` or `abstract class`

**Comment by pomadchin** [comment]
We finally replaced `scala-logging` with `log4s`.
