### ISSUE TITLE
RasterSource API feedback on resolutions member

### ISSUE THREAD

**Issue by echeipesh** [locationtech/geotrellis#3100]
This issue is based on discussion and feedback from @jisantuc

## Background

`RasterSource` interface provides list of available resolutions:
https://github.com/locationtech/geotrellis/blob/f811449e8342d86ffac8f6037643cc153e371f83/raster/src/main/scala/geotrellis/raster/RasterMetadata.scala#L49

The intent is to allow the user of the interface to reason which CellSizes are "safe" to use for resample and at what point the implementation will have to start reading progressively larger swaths of the raster to satisfy the read/resample request.

Incidentally it is theoretically possible that levels of detail or overviews reported in the `resolutions` list do NOT share the same extent. For instance when using `GeoTrellisRasterSource` each level of detail is stored as its own layer, which has its own metadata. The extent across zoom levels may or may not match either through error or design. Exposing `resolutions` as `GridExtent[Long]` allows the user to inspect that.

## Feedback

In code:

```scala
def testTiff(url: String) = {
  import geotrellis.raster.gdal.GDALRasterSource;
  val rasterSource = GDALRasterSource(url)
  val idealResolution = rasterSource.resolutions.minBy(res => scala.math.abs(250000 - res.rows * res.cols))
  val tile = rasterSource.read(idealResolution.gridBounds).get.tile
}
```

Following the types it is easy to mis-use the `read` method.
`read(grid: GridBounds)` reads relative to pixel bounds of the raster. `GridExtent` representing resolution also has `GridBounds` instance that basically represents the pixel size of the region. It is always indexed by (minCol=0, minRow=0).

Expected result in this case might be: read me the overview at resolution I have picked (say for thumbnail)
Actual result: read upper left corner from the image of same size as the pixel size of the resolution.

## Conclusions

In idea scenario types could not be connected like this to do nonsense operations. Possible solution:
- Change `resolutions` from `List[GridExtent]` to `List[CellSize]`
- Remove `gridBounds` method from `GridExtent`

Read method overloads are a little confusing:

`read(extent)` reads based on map extent
`read(gridBounds)` reads based on pixel extent

Consider renaming all overloads to `readExtent` and `readBounds` so it is more obvious from reading the code how the read is performed.

**Comment by echeipesh** [comment]
## GridExtent should not have .gridBounds

Exploring this idea further.
Semantically `GridBounds` instance has two related meanings in GT codebase.
1. `GridBounds` is subset of some pixel grid of some size, its upper left corner can be anywhere in relationship to the grid.
2. `GridBounds` describes a pixel grid, it this context it is always offset by (0, 0) in upper left corner.

`rasterExtent.gridBounds` and `gridExtent.gridBounds` is always the latter. Confusion between these two cases is partially responsible for the problem above. `GridBounds` on resolution describe SOME canvas, but are being used to read the pixels described by `RasterSource`.

### Analysis

`gridExtent.gridBounds` is used in following ways through-out our codebase which likely reflect overall usage pattern.

**Case 1**: `gridExtent.gridBounds` is used to check for intersection with another instance of `GridBounds` before doing some kind of read or subsetting operation. This is easily 80% of all usages.

https://github.com/locationtech/geotrellis/blob/7cf9bdaf1b7b1de573b94e828325495d51a912e0/store/src/main/scala/geotrellis/store/GeoTrellisReprojectRasterSource.scala#L105-L109

**Case 2**: `gridExtent.gridBounds` is used to read the raster using a subset operation. This happens occasionally, mostly as default value and in tests.

https://github.com/locationtech/geotrellis/blob/7cf9bdaf1b7b1de573b94e828325495d51a912e0/gdal/src/main/scala/geotrellis/raster/gdal/GDALDataset.scala#L308-L312

**Case 3**: `gridExtent.gridBounds` used to perform logical operation on full tile like slit

## Proposal
```scala
// stay tuned
```

**Comment by pomadchin** [comment]
Just a note, that `GridBounds` in `RasterSources` are coming from the fact, that `RasterSources` extend [CellGrid](https://github.com/locationtech/geotrellis/blob/master/raster/src/main/scala/geotrellis/raster/Grid.scala#L27). So this change is much more significant and can have a significant impact on the entire `RasterSources` API.

**Comment by pomadchin** [comment]
Just a note that both `GridExtent` and `RasterSources` extend [Grid](https://github.com/locationtech/geotrellis/blob/master/raster/src/main/scala/geotrellis/raster/Grid.scala#L27) and this can have a huge impact on the all API.

**Comment by pomadchin** [comment]
It looks like just adding the note above only adds ambiguity. Leaving a detailed feedback on the @echeipesh proposal & on the API in general.

### I will start from the end, about API overloads: 
`RasterSources` API already provides overloads to [readExtents / readBounds](https://github.com/locationtech/geotrellis/blob/master/raster/src/main/scala/geotrellis/raster/RasterSource.scala#L146-L164), the suggestion here would be to use them and not to use other overloads. In fact in `RasterSources` API all overloads / function aliases will hit `readBounds` overloads. 

However, we need to cleanup [GeoTiffRasterSources](https://github.com/locationtech/geotrellis/blob/master/raster/src/main/scala/geotrellis/raster/geotiff/GeoTiffRasterSource.scala#L67-L79) to make it more obvious why we can't re-use `readBounds` here or fix it to reuse `readBounds`.

### Changing `resolutions` from List[GridExtent] to List[CellSize]

As it has been said, GeoTiff overviews _may have_ a different extent. `GeoTrellis layers` that are read by the `GeoTrellis RasterSource` can also have different `Extents`, initially, because of these reasons we decided to expose overviews not just as a `CellSize` but a as a `RasterExtent`.

I would agree that _resolutions_ indeed should return _resolutions_ as a `List[CellSize]`, and if we still need .

### GridExtent should not have .gridBounds (@echeipesh proposal add-on)
I like the idea, it makes API cleaner and easier to use. 

However it can be a non trivial problem, since both `GridExtent` and `RasterSources` extend [Grid](https://github.com/locationtech/geotrellis/blob/master/raster/src/main/scala/geotrellis/raster/Grid.scala#L27) (that is why we _need_ to have `GridBounds` exposed) and this can have a huge impact on the entire API. I am not sure what the consequences would be: it can be an easy move or it can be a hard one. Actually, this was one of the reasons why we decided not to include [RasterSourceF](https://github.com/geotrellis/geotrellis-contrib/blob/develop/vlm/src/main/scala/geotrellis/contrib/vlm/effect/RasterSourceF.scala) in the GeoTrellis core - `RasterSourceF` does not extend a `CellGrid` anymore. 

We can be to try to remove `GridBounds` from the `Grid` type to see what would happen. 

:+1: to @echeipesh
