### ISSUE TITLE
Add more crs info in metadata when ingesting to catalog.

### ISSUE THREAD

**Issue by esmeetu** [locationtech/geotrellis#3174]
GT version: 2.3.1

When i ingest epsg:4490 tif into catalog, i found that the crs info is `"crs": "+proj=longlat +ellps=GRS80 +no_defs"` in metadata.json file. But in [proj4 epsg config file,](https://github.com/locationtech/proj4j/blob/master/src/main/resources/proj4/nad/epsg) there are many epsgcodes corresponding to that crs info. 
When reading metadata from attribute, it will choose the first epsgcode 4019 in the epsg file, which is not expected one. 
I suggest to add more crs info in metadata, like `"crs": "<4490> +proj=longlat +ellps=GRS80 +no_defs"`.
Related encode code:
```
geotrellis.spark.io.json.Implicits

implicit object CRSFormat extends RootJsonFormat[CRS] {
// Perhaps `crs.toWKT()` is better?
def write(crs: CRS) = JsString(crs.toProj4String) // change to JsString(s"<${crs.epsgcode.getOrElse(defaultValue)}> ${crs.toProj4String}"
```
Decode in readTileMetaData should also change based that convention.

**Comment by pomadchin** [comment]
Hey @esmeetu! 

Technically there is no mistake. If proj4 strings are the same - the [locationtech/proj4](https://github.com/locationtech/proj4j) lib will do the same thing for different EPSG codes.

[OSGeo/proj](https://github.com/OSGeo/PROJ/blob/6.3.0/include/proj/io.hpp#L633-L637) contains a notion here that convertation to a proj string leads to some data loss. 

So we can definitely consider switching to WKT, but it won't resolve the fact that we depend on the [locationtech/proj4](https://github.com/locationtech/proj4j) lib and switching to the WKT strings storage won't affect [locationtech/proj4](https://github.com/locationtech/proj4j) computation logic, since [locationtech/proj4](https://github.com/locationtech/proj4j) does not support WKT strings. It can even be considered as a [locationtech/proj4](https://github.com/locationtech/proj4j) enhancement.

**Comment by esmeetu** [comment]
thank you very much. @pomadchin 
It's hard for me to use custom attribute, because it will change much in my project code.
Is there a way to just override the implicit function `tileLayerMetadataFormat` in my own project instead of copying all the file? 
Hope u can get what i say.

**Comment by pomadchin** [comment]
Yep, just define it in the call scope and it will be picked up

**Comment by pomadchin** [comment]
I'm closing this issue for now, feel free to reopen it / to create new issues or to discuss it in our gitter channel!
