### ISSUE TITLE
ShortUserDefinedNoDataArrayTile.cols()/rows() calls scala/runtime/BoxesRunTime.boxToInteger

### ISSUE THREAD

**Issue by metasim** [locationtech/geotrellis#3427]
Details and test case to come, but right now it appears that calls to `rows()` and `cols()` box the return values.

`:javap` output 

```scala
 public java.lang.Object rows();
    descriptor: ()Ljava/lang/Object;
    flags: (0x1041) ACC_PUBLIC, ACC_BRIDGE, ACC_SYNTHETIC
    Code:
      stack=1, locals=1, args_size=1
         0: aload_0
         1: invokevirtual #186                // Method rows:()I
         4: invokestatic  #184                // Method scala/runtime/BoxesRunTime.boxToInteger:(I)Ljava/lang/Integer;
         7: areturn
      LineNumberTable:
        line 146: 0
      LocalVariableTable:
        Start  Length  Slot  Name   Signature
            0       8     0  this   Lgeotrellis/raster/ShortUserDefinedNoDataArrayTile;

  public java.lang.Object cols();
    descriptor: ()Ljava/lang/Object;
    flags: (0x1041) ACC_PUBLIC, ACC_BRIDGE, ACC_SYNTHETIC
    Code:
      stack=1, locals=1, args_size=1
         0: aload_0
         1: invokevirtual #178                // Method cols:()I
         4: invokestatic  #184                // Method scala/runtime/BoxesRunTime.boxToInteger:(I)Ljava/lang/Integer;
         7: areturn
      LineNumberTable:
        line 146: 0
      LocalVariableTable:
        Start  Length  Slot  Name   Signature
            0       8     0  this   Lgeotrellis/raster/ShortUserDefinedNoDataArrayTile;
```

![image](https://user-images.githubusercontent.com/4929546/138466715-af79721d-f677-49a2-8e59-52a742326a1b.png)

**Comment by pomadchin** [comment]
We did a tiny research with @metasim: RF does a lot of upcasts to the `CellGrid[Int]` type which leads to ineffective cols / rows / etc, calls since `Grid` and `CellGrid` are not specialized by `Int` / `Long`. In case the `Tile` is upcasted to it we loose any meta about the specialized version that allows to avoid unboxing. 

The solution is probably to add specialization by `Int` and `Long` to Grid and CellGrid.

Long is needed since the whole idea of this N was to add an ability to work with Longs. (if I don't remember it wrong).
