### ISSUE TITLE
File size larger than expected when using GeoTiff().writer to output Tif file

### ISSUE THREAD

**Issue by WKX-w** [locationtech/geotrellis#3527]
## Describe the bug
I use the GeoTiff().writer function to output a Tiff image with dimensions of 259×259 and pixel values of Float64. Under normal circumstances, the size of the image should be 524KB, but the actual output is 2049KB. What could be the reason for this, and does Geotrellis output Tif files with a fixed size?
![image](https://github.com/locationtech/geotrellis/assets/75596612/bfb9f4c8-55a9-4d82-b231-b04c0ca12462)
![image](https://github.com/locationtech/geotrellis/assets/75596612/ec1ef191-b90e-495d-a4c9-44cf34e43c9d)
![image](https://github.com/locationtech/geotrellis/assets/75596612/ccd77860-7c4e-4b22-bff3-1f2d4cd8fc28)

**Comment by pomadchin** [comment]
Ha, that's a good catch. I was not able to reproduce 2mb, only 1mb. 

The reason for that is the TIFF tiled layout specified before write (256 by default) and the TIFF size 259. 

As the result this TIFF has 4 segments 256 x 256 each that results in 1mb result TIFF. 

I don't really remember specifics, but I guess just a very unfortunate combination of the layout scheme + tile size for our writer.

Try the code below to see the expected tiff size:

```scala
val (cols, rows) = (259, 259)
val tile = ArrayTile(Array.fill(cols * rows)(0f), cols, rows)
val extent = Extent(0, 0, cols, rows)

val raster = Raster(tile, extent)
val tiff = SinglebandGeoTiff(tile, extent, LatLng, Tags.empty, GeoTiffOptions.DEFAULT.copy(Tiled(259, 259)))

tiff.write("/tmp/zeros.tiff", true)
```

GDAL on the other hand ueses a Striped layout scheme by default:

```bash
gdal_create -ot Float32 -outsize 259 259 -bands 1 -burn 0 out.tiff
# with the gdalinfo output
Band 1 Block=259x7 Type=Float32, ColorInterp=Gray
```

^ To achieve the same affect instead of a tiling scheme we could store tiff segments striped:

```scala
val tiff = SinglebandGeoTiff(tile, extent, LatLng, Tags.empty, GeoTiffOptions.DEFAULT.copy(Striped(259, 259)))
```

**Comment by pomadchin** [comment]
Oh, I see now, 2mb makes sense since in the question it's all about Float64 (Double) and in my example that's been Float32 (Float). 

All makes sense now; so in my response above just multiple all numbers x2.

**Comment by WKX-w** [comment]
I see. Thank you very much!
